###################################################################

#Points

#Config v1.0
###################################################################

host: "mineweb"
name: "root"
pass: "pass"
dbName: "dbName"
port: 3306

