name: OpsyPoints
version: 1.0
author: ZeTioZ
main: fr.opsycraft.OpsyPoints.main
commands:
  points:
    aliases: [pts]
    description: Voir les commandes disponibles
  chestbuy:
    description: Permet d'acheter des coffres
  exchange:
    aliases: [echange, convertir, conv, convertisseur, hto]
    description: Convertit de l'argent en jeu avec des points boutique
permissions:
  points.set:
    default: op
    description: Mettre de l'argent admin
  points.add:
    default: op
    description: Ajouter de l'argent
  points.remove:
    default: op
    description: Retirer de l'argent
  points.shop:
    default: op
    description: Regarder le shop ingame